import Head from 'next/head'

function Home() {
  return (
    <>
      <Head>
        <title>AframeHotel</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link
          type="image/svg"
          rel="icon"
          sizes="32x32"
          href="/img/aframeIcon.jpg"
        />
      </Head>
    </>
  )
}

export default Home
